# Generated by Django 4.1.7 on 2023-03-21 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness_app', '0002_favorite_favorite_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fitnessprogramm',
            name='intensity',
            field=models.CharField(blank=True, choices=[('Pas daraja', 'Pas daraja'), ('Vashee qiyin daraja', 'Vashee qiyin daraja'), ("O'rtancha daraja", "O'rtancha daraja"), ('Kotta daraja', 'Kotta daraja')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='fitnessprogramm',
            name='part_of_body',
            field=models.CharField(blank=True, choices=[("Qo'l", "Qo'l"), ("Ko'krak", "Ko'krak"), ('Bel', 'Bel'), ('Qorin', 'Qorin'), ('Oyoq', 'Oyoq')], max_length=100, null=True),
        ),
    ]
