# Generated by Django 4.1.6 on 2023-03-30 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness_app', '0003_alter_fitnessprogramm_intensity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteinfo',
            name='about_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='siteinfo',
            name='about_uz',
            field=models.TextField(null=True),
        ),
    ]
