# Generated by Django 4.1.6 on 2023-04-06 03:53

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness_app', '0005_article_context_en_article_context_uz_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteinfo',
            name='about_en',
        ),
        migrations.RemoveField(
            model_name='siteinfo',
            name='about_uz',
        ),
        migrations.AddField(
            model_name='article',
            name='slug_en',
            field=models.SlugField(null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='slug_uz',
            field=models.SlugField(null=True),
        ),
        migrations.AddField(
            model_name='favorite',
            name='favorite_slug_en',
            field=models.SlugField(null=True),
        ),
        migrations.AddField(
            model_name='favorite',
            name='favorite_slug_uz',
            field=models.SlugField(null=True),
        ),
        migrations.AddField(
            model_name='favorite',
            name='favorite_title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='favorite',
            name='favorite_title_uz',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='fitnessprogramm',
            name='context_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='fitnessprogramm',
            name='context_uz',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='fitnessprogramm',
            name='slug_en',
            field=models.SlugField(null=True),
        ),
        migrations.AddField(
            model_name='fitnessprogramm',
            name='slug_uz',
            field=models.SlugField(null=True),
        ),
        migrations.AddField(
            model_name='fitnessprogramm',
            name='title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='fitnessprogramm',
            name='title_uz',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
