# Generated by Django 4.2 on 2023-04-08 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitness_app', '0006_remove_siteinfo_about_en_remove_siteinfo_about_uz_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fitnessprogramm',
            name='slug_en',
        ),
        migrations.RemoveField(
            model_name='fitnessprogramm',
            name='slug_uz',
        ),
        migrations.RemoveField(
            model_name='siteinfo',
            name='about',
        ),
    ]
